on:
  push:
    branches:
      - main
      - st/export-wallet

name: release-latest
jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          check-latest: true
      - run: yarn
      - name: mark latest
        uses: ./.github/actions/mark-latest

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          use_vue_cli: true
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          mac_certs: ${{ secrets.MAC_CERTS }}
          mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
          args: "--publish=never"
      - name: Move Files
        shell: bash
        run: ./move_dist.sh

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: olympia-wallet-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v1
        if: matrix.os == 'macOS-latest'
        with:
          name: olympia-wallet-mac
          path: dist-mac

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: olympia-wallet-win
          path: dist-win
